### ISSUE TITLE
error when installing install.sh

### ISSUE THREAD

**Issue by redboyke** [song31/comix-server#3]
::::::::::::::::::::::::
 2. Configure comix
::::::::::::::::::::::::
::::::::::::::::::::::::
 3. Configure Apache
::::::::::::::::::::::::
ERROR: File /usr/syno/apache/conf/httpd.conf-user does not exist.
ERROR: File /usr/syno/apache/conf/httpd.conf does not exist.
::::::::::::::::::::::::
 4. Configure PHP
::::::::::::::::::::::::
ERROR: File /usr/syno/etc/php/user-setting.ini does not exist.
::::::::::::::::::::::::
 5. Restart HTTPD
::::::::::::::::::::::::
Wait 5 seconds...
./install.sh: line 112: /usr/syno/apache/bin/httpd: not found
DiskStation>

i have a DS212+ running the latest version of DSM 5.0
hope this gets fixed or someone knows how to fix it.
cause the java version of air comic server isnt working either on synology but it works on windows.

**Comment by fernandofbamzn** [comment]
Hi, 
I am trying to install it on DSM 5.x. I modified the following lines
WEB_DIR="/var/services/web/comix-server"
APACHE_CONF="/etc/httpd/conf/httpd.conf"
PHP_CONF="/etc/php/conf.d/user-settings.ini" #"/usr/syno/etc/php/user-setting.ini"
APACHE_CMD="/usr/bin/httpd -DHAVE_PHP"
TEMP_DIR="/tmp"
SOURCE="https://github.com/song31/comix-server/archive/master.zip"

when i execute install.sh, it crash at the end.

Wait 5 seconds...
(98)Address already in use: make_sock: could not bind to address [::]:80
(98)Address already in use: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
Unable to open logs

**Comment by song31** [comment]
@redboyke and @fernandofbamzn Just updated install script to support DSM 5.x. Please try to install using the latest install.sh and let me know if you still have problems.

**Comment by song31** [comment]
Differences between DSM 4 and 5 are:
- Apache & PHP file path
- PHP user-settings.ini content ("display_errors = Off" should be there)
- Default directory permission when created (manga directory permission should be 755)

New install script will handle all of them correctly after detecting the DSM version.

**Comment by redboyke** [comment]
i have DSM 5.1-5022
i have changed manga to Comics in index.php
in http.conf-comix and install.sh because i have /volume1/Comics

DiskStation> cd /volume1/Comics
DiskStation> chmod 755 install.sh
DiskStation> ./install.sh
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 1. Detecting DSM Version
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
ERROR: Cannot detect DSM Version. Exiting...
DiskStation>

**Comment by song31** [comment]
@redboyke What is "majorversion" in /etc/VERSION? If you don't have such file, you can create by the following command:

echo "majorversion=5" > /etc/VERSION

**Comment by redboyke** [comment]
i have a DS212+
info in the file is:
majorversion="3"
minorversion="2"
buildphase="0"
buildnumber="1958"
builddate="2011/12/15"

**Comment by song31** [comment]
Hmm... You can change it to 5 and try again.

**Comment by redboyke** [comment]
ok the install worked.
what android app can i use with this?
and how do i make a htpassword file on windows?

**Comment by fernandofbamzn** [comment]
Thanks you!!
it's working. But now, I can't access to read my comics. any help?

**Comment by song31** [comment]
There are many website that can generate hapassword file for you:

http://www.htaccesstools.com/htpasswd-generator-windows/

Comix-server is for AirComics iOS app!
