### ISSUE TITLE
Air Comic Viewer - File Not Found!

### ISSUE THREAD

**Issue by fernandofbamzn** [song31/comix-server#4]
Hi,
I am trying to access the server comic and I get this message.
if I put in the 192.168.1.12:31257/Comics browser, I see the folders that have the comics:
Civil War The Incredible Hercules Vol1 StarWars Ultimate Marvel Zombies Spiderman Black Widow and the Marvel Girls

But in the Air Comic Viewer no way to configure it.

I have put this:
       Type: AirComicServer
       Address: 192.168.1.12:31257/Comics
       Port: 31257
       Password:
       user ID

**Comment by song31** [comment]
You need to put only the IP address in the Address field.

**Comment by fernandofbamzn** [comment]
If i set that, it send the following message: "Invalid Message"
I'm using Air Comic Viewer, from an Android device.

**Comment by song31** [comment]
@fernandofbamzn comix-server is not for Android Air Comic Viewer. It is for iOS AirComix. They are totally different.
