### ISSUE TITLE
sh: 0: Can't open install.sh

### ISSUE THREAD

**Issue by ccccdd** [song31/comix-server#7]
when i run  sudo apt-get install python imagemagick libopencv-core2.3 libopencv-highgui2.3
and it make a  mistake.
so i am try the    apt-get install python imagemagick libopencv-core2.4 libopencv-highgui2.4
![20151022182918](https://cloud.githubusercontent.com/assets/15207024/10661752/e5f34686-78ea-11e5-9cdb-cc1ad48c4d1a.png)
Then follow down to do ...
After running this command, （sh install.sh）the emergence of new problems
![2](https://cloud.githubusercontent.com/assets/15207024/10661835/58b378d0-78eb-11e5-9ad4-f61438262413.png)
Can someone help me please...

**Comment by ccccdd** [comment]
@martin-frbg  @xianyi hi,Can you help me?

**Comment by martin-frbg** [comment]
Do "ls -l install.sh" to see if the file exists there. Are you sure that it should be in src ? 
(But I have no idea what comix-server even is)

**Comment by song31** [comment]
@ccccdd You should run where the file, install.sh exists.
